version: '3'
services:
  eureka-master:
    build:
      context: ./
      dockerfile: Dockerfile
    image: springcloud:latest
    container_name: eureka-master
    entrypoint: java -jar -Dspring.profiles.active=master eureka-server.jar
    ports:
      - 8001:8001

  eureka-replica1:
    image: springcloud:latest
    container_name: eureka-replica1
    entrypoint: java -jar -Dspring.profiles.active=replica1 eureka-server.jar
    ports:
      - 8002:8002
    depends_on:
      - eureka-master

  #  eureka-replica2:
  #    image: springcloud:latest
  #    container_name: eureka-replica2
  #    entrypoint: java -jar -Dspring.profiles.active=replica2 eureka-server.jar
  #    ports:
  #      - 8003:8003
  #    depends_on:
  #      - eureka-master

  #  eureka-client:
  #    image: springcloud:latest
  #    container_name: eureka-client
  #    entrypoint: java -jar eureka-client.jar
  #    ports:
  #      - 8102:8102
  #    depends_on:
  #      - eureka-master

  user-service:
    image: springcloud:latest
    container_name: user-service
    entrypoint: java -jar -Dserver.port=8201 user-service.jar
    ports:
      - 8201:8201
    depends_on:
      - eureka-master

#  user-service2:
#    image: springcloud:latest
#    container_name: user-service2
#    entrypoint: java -classpath common-SNAPSHOT.jar -jar -Dserver.port=8202 user-service.jar
#    ports:
#      - 8202:8202
#    depends_on:
#      - eureka-master

#  ribbon-service:
#    image: springcloud:latest
#    container_name: ribbon-service
#    entrypoint: java -classpath common-SNAPSHOT.jar -jar -Dserver.port=8301 ribbon-service.jar
#    ports:
#      - 8301:8301
#    depends_on:
#      - eureka-master

  hystrix-service:
    image: springcloud:latest
    container_name: hystrix-service
    entrypoint: java -jar -Dserver.port=8401 hystrix-service.jar
    ports:
      - 8401:8401
    depends_on:
      - eureka-master
