version: '3'
services:
  eureka-master:
    build:
      context: ./
      args:
        - profile=master
      dockerfile: eureka-server.dockerfile
    image: eureka-server:master
    container_name: eureka-master
    entrypoint: java -jar -Dspring.profiles.active=master eureka-server.jar
    ports:
      - 8001:8001

  eureka-replica1:
    build:
      context: ./
      args:
        - profile=replica1
      dockerfile: eureka-server.dockerfile
    image: eureka-server:replica1
    container_name: eureka-replica1
    entrypoint: java -jar -Dspring.profiles.active=replica1 eureka-server.jar
    ports:
      - 8002
    depends_on:
      - eureka-master

  eureka-replica2:
    build:
      context: ./
      args:
        - profile=replica2
      dockerfile: eureka-server.dockerfile
    image: eureka-server:replica2
    container_name: eureka-replica2
    entrypoint: java -jar -Dspring.profiles.active=replica2 eureka-server.jar
    ports:
      - 8003
    depends_on:
      - eureka-master

  eureka-client:
    build:
      context: ./
      dockerfile: eureka-client.dockerfile
    image: eureka-client:latest
    container_name: eureka-client
    ports:
      - 8102
    depends_on:
      - eureka-master
      - eureka-replica1
      - eureka-replica2