version: '3'
services:
  eureka-master:
    build:
      context: ./
      args:
        - profile=master
      dockerfile: eureka-server.dockerfile
    image: eureka-server:master
    container_name: eureka-master
    ports:
      - 8001:8001

  eureka-replica1:
    build:
      context: ./
      args:
        - profile=replica1
      dockerfile: eureka-server.dockerfile
    image: eureka-server:replica1
    container_name: eureka-replica1
    ports:
      - 8002

  eureka-replica2:
    build:
      context: ./
      args:
        - profile=replica2
      dockerfile: eureka-server.dockerfile
    image: eureka-server:replica2
    container_name: eureka-replica2
    ports:
      - 8003

  eureka-client:
    build:
      context: ./
      dockerfile: eureka-client.dockerfile
    image: eureka-client:latest
    container_name: eureka-client
    ports:
      - 8102