server:
  port: 8201
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-master:8001/eureka/,http://eureka-replica1:8002/eureka/,http://eureka-replica2:8003/eureka/