server:
  port: 8002
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-replica1
  client:
    serviceUrl:
      defaultZone: http://zhfk:123456@eureka-master:8001/eureka/,http://zhfk:123456@eureka-replica2:8003/eureka/
    fetch-registry: true
    register-with-eureka: true