server:
  port: 8001 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  security:
    user:
      password: 123456
      name: zhfk
eureka:
  instance:
    hostname: eureka-master #指定主机地址
  client:
    serviceUrl:
      defaultZone: http://eureka-replica1:8002/eureka/,http://eureka-replica2:8003/eureka/
    fetch-registry: true #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: true #指定是否要注册到注册中心（注册中心不需要开启）
  server:
    enable-self-preservation: false #关闭保护模式
