server:
  port: 8003
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: eureka-replica2
  client:
    serviceUrl:
      defaultZone: http://zhfk:123456@eureka-master:8001/eureka/,http://zhfk:123456@eureka-replica1:8002/eureka/
    fetch-registry: true
    register-with-eureka: true